name: learn-easy-apk-test
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  app-start-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-app
        uses: actions/checkout@v4
      - name: install-environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
        env:
          DB_URL:  ${{ vars.DB_URL }}
          CLOUD_NAME:  ${{ vars.CLOUD_NAME }}
          CLOUD_API_KEY:  ${{ vars.CLOUD_API_KEY }}
          CLOUD_API_SECRET:  ${{ vars.CLOUD_API_SECRET }}
          SECRET_KEY:  ${{ vars.SECRET_KEY }}
          GMAIL:  ${{ vars.GMAIL }}
          G_PASS:  ${{ vars.G_PASS }}
          WEB_TOKEN:  ${{ vars.WEB_TOKEN }}
          API_URL:  ${{ vars.API_URL }}
      - name: database-url
        run: echo ${{ vars.DB_URL }}
      - name: Run application
        run: npm start
